### ISSUE TITLE
How to fix OTClient not opening on older pc models

### ISSUE THREAD

**Issue by cjrz74** [edubart/otclient#1019]
A lot of people have the problem of OTClient not opening on older PC and laptop models.

Konrad(Medevia) seems to have an obsession with closing these issues.. seems fixed on his server? XD

This is how you fix it :)

Go into Properties / C/C++ / Code generation and change 'Enable Enhanced Instruction Set' to SSE2

https://i.imgur.com/JZHcg6I.png

**Comment by iryont** [comment]
Definitely that must be the case. It has nothing to do with your ability to provide enough logs of the issue rather than spamming issues section with "my client doesn't start! Fix it for me!".

I will keep this repository as clean as possible and organized as much as possible as long as I'm here. If you provide enough logs of the issue I will always try to help you locate the problem, but that requires some willingness to at least debug the problem rather to expect everything to be taken care of for you.

Also, the "issue" you have described is not an issue. It is your own choice to compile the game client with requested instructions. If you want to compile something you need at least basic understanding of what you are doing.

**Comment by cjrz74** [comment]
Go reset Pendulum again.

To everyone I suggest using this repository instead https://github.com/otland/otclient

**Comment by iryont** [comment]
I'm afraid without logs it is impossible to have any hint of what was causing issue since there can be multiple reasons, so you cannot expect anyone or me to fix the issue without having any useful information for that matter. Anyway, instead of wasting your time on accusations you should spend some time on creating PR instead (why you didn't do that in the first place I have no idea). I would gladly merge it into the main repository. Anyway, I will do it for you, since I now I know what was causing the issue (AVX instructions).

**Comment by cjrz74** [comment]
<3
