### ISSUE TITLE
Corpse causing tile draw issue

### ISSUE THREAD

**Issue by theshibbies** [edubart/otclient#1040]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Create 64x64 corpse (Cyclops or GS for example)
2. Move near another 64x64 item (fir tree for example) so that parts of the corpse will overlap onto parts of the existing item 
3. You will see in certain positions the corpse will be stacked on top of the item and your player will be drawn on top of the existing item as well

### Expected behaviour
Your character should always be drawn underneath the existing 64x64 item and in some instances the corpse should be down below the existing item

### Actual behaviour
Your character will be drawn above the existing 64x64 item and in some cases the corpse is drawn above the existing item where it should not be

### Environment
TFS 1.3 / Client Version 10.98

![sprites](https://user-images.githubusercontent.com/43316702/60763438-799b0900-a042-11e9-93a8-1e1836f0d14c.png)

-- Extra issue that I assume involves the same code which happens with items with top flag.
![51724187-2b60f300-202a-11e9-9899-39b8ce731ae0](https://user-images.githubusercontent.com/43316702/60763439-7c95f980-a042-11e9-9e92-cb0e81ab5075.gif)

The issue seems to mainly lie within the Tile::draw function within tile.cpp. However I cannot seem to figure out how to fix it. Any insight would be helpful.

**Comment by Ochmar** [comment]
Cipsoft has same problems (well, they have different problems but I believe the root stays the same for both):
https://i.imgur.com/YppDbBp.png
Also, I noticed that this is kind of drawing problem while using stairs (or anything that has elevation). And this time cipsoft solved it, by... adding wall behind stairs so it won't bug.
https://i.imgur.com/1J5k3bN.png

**Comment by iryont** [comment]
Well, in general it is not easy task to fix it. You can change the drawing order to horizontal from left to right and from top to bottom or an actual diagonal one (drawing from top-left to bottom-right going diagonally), however, despite the fact that those drawing orders do fix certain cases which were described here (e.g. the stairs in @Ochmar post), but they do bring other issues. The point is it's always a trade-off unless some more advanced ordering algorithm is used.

Corpses wider than 1x1 are yet another issue which do require re-drawing certain tiles, so e.g. character stays always on top of the corpse (despite it being drawn after the character). Personally I did remove this as it w as unnecessary waste of performance which didn't even bring expected results:

https://github.com/edubart/otclient/blob/master/src/client/tile.cpp#L108
https://github.com/edubart/otclient/blob/master/src/client/tile.cpp#L119

If you get enough corpses on your screen the game client will probably re-draw most of the tiles two times or even more.

I will probably remove this code from the repository as it doesn't bring anything good.

**Comment by Ochmar** [comment]
I would opt against.
I mean, I know it's not easy, and every solution has it downsides, but way out you are suggesting has one (big, in my opinion) problem. Player "falls" under corpse:
https://i.imgur.com/JXGSQP1.png
This is stylistically unpleasing (and it's not how cipsoft handled it if that matters for anyone). And from all the ways I got, I think this is the one that interfere into gameplay the most (this is arguable tho). Please keep in mind that this is just my opinion, so other guys would rather have this downside rather than different ones.

I do agree about the waste of performance part, however. For this I would mark tile with some flag "hasLyingCorpse" in protocolgame (and then skip those tiles in re-drawing, since they would get "good" result after first draw), but rather than fixing performance, I would first focus on the main problem first.
And the problem is that I think there should be some flag that should point to "those items should be redrawn if corpse is lying nearby", because there are "some" specific items (i.e. hangable torch/blackboard) that despite being just "items", those should be redrawn, and then there are some stones etc, which are the same "item category" as torch/blackboard, but those should not be redrawn.
The more I think about this algorithm the more I think that **items** (those that are getting drawn by "DrawItems") should have some flag "redraw" order with options like "NoRedraw", "RedrawUnder", "RedrawOnTop" and so on or different ones, I haven't study all the cases.

But as it is for today, I totally resign from redrawing tiles at all.
I might come back to this once I find more time, tho.

**Comment by iryont** [comment]
It's dealer's choice, really. I'm not suggesting anything, but rather I'm stating a simple fact that this code is simply not working properly. I find it more glitchy than being useful at this point (especially when you take a look at examples the author of this issue has provided).

Also, you are overestimating the impact it has on the game though (character being drawn under the corpse). I've been rendering objects like that for years and I honestly cannot remind myself of any report from player within last years about it. However, the moment I did change the drawing order to fully diagonal one which created a specific issue in which vertical walls with hangable objects were overlapped by bigger objects rendered on the right of them then it was immediacy reported by several players because in rather rare scenarios they had their hangables being partially drawn under those objects.

Anyway, that being said I'm looking forward to anyone actually contributing something here. If it's good enough I will gladly merge it into the master :)

**Comment by Ochmar** [comment]
It's hard to disagree with your conclusions.
I spent one and a half day and there's thought that keeps repeating in my mind that there are some missing attributes for each item (attributes about redrawing) to get it **right and stylistically pleasing**. And yet, if we add attributes to (some) items, **that'll feel a mess** and is not a right thing to do. I think what's messed up is Cipsoft's logic, not OTClient's.
I feel like those two are excluding ourselves each time I try to make it different.

I created pull request https://github.com/edubart/otclient/pull/1070 to delete it, because performance-wise I believe it's way better. Also, gameplay-wise it's constant - contrary to redrawing those tiles which had some weird mixed feelings which felt like "bugs".

I will for sure comeback to this issue once I get more time, but for now I cannot help but delete those redrawing. Solving this issue requires time, knowledge about "what should be redrawn and what no" and some idea about items in TFS world.

**Comment by iryont** [comment]
You are right. We are missing too many things to make it work properly. Even if we change the technique how we draw tiles to layer rendering (ground -> borders -> walls -> ...) then despite fixing issues with e.g. corpses (since creatures would always be drawn after items) it will bring some other glitches.

The fact is we can never draw from right to left due to the projection the game client uses. However, in certain cases it is desired for an item on the left tile to be drawn after the item on the right tile (or a deferred draw). That's a contradiction and it cannot be easily solved. Certainly not by a simple tile redraw.

I honestly doubt anyone will fix it as the repository seems rather deserted and everyone expects things to be handed to them, but if anyone attempts to I will gladly help with it.

**Comment by iryont** [comment]
Anyway, we can mark this issue as "fixed" by #1070
