### ISSUE TITLE
[suggestion] use lua instead of otml for settings

### ISSUE THREAD

**Issue by Zbizu** [edubart/otclient#1067]
This is mainly for settings file, I didn't check if there are other otmls, but settings file would be a great place to begin.

File location (windows): c:/users/username/otclient/config.otml 

Current problems:
- settings completely reset when fail to load at some point of file
- forced 4 spaces format
- separate parser needed when we have lua right under our noses

Benefits of having it in lua:
- comfortable table format for settings
- all kinds of strings possible (otml doesn't allow strings starting from space and empty strings)
- code tabbing
- native lua functions can be used to load it
- easier to develop
- less likely to break for no reason
- easier to debug

Was there any particular reason why lua wasn't used for it?

**Comment by edubart** [comment]
>  settings completely reset when fail to load at some point of file

this only occurs if the file is corrupt, if this is happening I think you have worse problems.

>  forced 4 spaces format

actually is 2 spaces indentation

> separate parser needed when we have lua right under our noses

parsing sure should be easy using `loadfile()`, but emitting the config back is not there you would have to implement and handle many corner cases

> This is mainly for settings file

parsing configs generated by application in lua also is full of security issues, like the user could inject undesired code (like hacks) in the config, sandboxing in lua could solve this matter but usually comes with security holes left by developer 

> comfortable table format for settings

I think you are using config or OTML for the wrong thing

> all kinds of strings possible (otml doesn't allow strings starting from space and empty strings)

otml does allows it, it has escaping string mechanisms like YAML, learn it,
or if you think you really found an issue then report it or fix instead of reinventing the whole thing

> native lua functions can be used to load it

I think you are wanting to use the config for the wrong thing, why one would need that in a config? even though look the .OTUI files they are actually OTML files and uses lua functions for some UI events

> code tabbing

I think you don't know how to configure you editor to use two spaces indentation

> easier to develop

OTML does use indentation to differ scopes and is much easier on the eyes to configure UIs,
otclient did start with Lua config files for UI and other stuff, and trust me was way worse and unpleasant to type UI

> less likely to break for no reason

it would only break if you misuse it, and again if you find anything is really broken report the issue or work on the fix, and OTML is very stable look the code base there is tons of UI files using it

> easier to debug

just read the error messages..

> Was there any particular reason why lua wasn't used for it?

it was at first, just way boilerplate and unpleasant to type UIs

**Comment by edubart** [comment]
I would like to added too that today **YAML** format is used everywhere in the industry, because developers love how clean and readableit is. And **OTML** is actually a much simpler implementation of it, it was creating reading the YAML specification, but mainly implemented features that otclient needed and with some additions to allow to declare more readable UI files.

In the older days I did use a YAML parser for the client, but I needed to customize it to handle tags with repeated names to declare UIs, then OTML was created.

Actually there is a single header compact implementation of OTML at https://github.com/edubart/otml
One header with less than 1K lines, this sure is simpler then invoking a whole Lua parser and VM, or embedding a YAML or other external library.

**Comment by Zbizu** [comment]
Thank you for your insight.
I will try escape strings for #1064 instead (will pull request if I get a solid outcome).

**Comment by Xaekai** [comment]
> because developers love how clean and readable it is

No, developers hate YAML

[YAML: Not so great](https://www.arp242.net/yaml-config.html)
[hackernews agrees that not so great](https://news.ycombinator.com/item?id=17358103)
[Definitive guide to hating YAML](https://noyaml.com/)
[Stop Using YAML](https://dev.to/jessekphillips/stop-using-yaml-3kec)
[Mission Impossible Self Destructor](https://alexwlchan.net/2019/12/yaml-impossible/)
[The Norway Problem](https://hitchdev.com/strictyaml/why/implicit-typing-removed/)
[Red Hat hates YAML and uses Python and JSON instead](https://www.redhat.com/sysadmin/yaml-tips)
[YAML sucks](https://github.com/cblp/yaml-sucks)
[Reddit agrees that YAML sucks](https://www.reddit.com/r/programming/comments/7ctwi7/yaml_sucks/)
[Shirt](https://www.redbubble.com/i/hoodie/YAML-is-the-answer-to-the-question-no-one-asked-what-if-JSON-was-shittier-by-unixorn/25705086.O16E3) (no affiliation, rb doesn't carry my size)

Developers only use YAML because the alternatives suck worse.
