### ISSUE TITLE
Movement Lag

### ISSUE THREAD

**Issue by Ancores** [edubart/otclient#636]
I'm experiencing a .3~ sec lag every step I take when walking.
Doesn't seem to matter how much movement speed I have.

It has nothing to do with connection to the server or computer lag, since it's local host and a high-end computer.
It's unplayable like this for me.

Doesn't matter what kind of movement I do (walk, dashWalk or autoWalk).

Latest OTC build
Client 10.41

**Comment by Anastaciaa** [comment]
Can you make short movie about how it looks exactly?

**Comment by Ancores** [comment]
It's pretty hard to see on the video, but here it is.
https://www.youtube.com/watch?v=Y3DlyjPMAuk&feature=youtu.be

**Comment by LordHepipud** [comment]
Can you try that out with Cipsofts Client and check if the problem persists there? I had a similar issue on my server with movement and it was actually caused by the server itself as the movement handling is not handeled properly.

Once I chanced it the client worked fluently. But I can't tell if that was just me or the client really is having a bug there.

~~~~Lord Hepipud~~~~

**Comment by TheSumm** [comment]
Can't really tell the issue by watching the video.
Does this also happen with an unmodified version of Otclient?

**Comment by Anastaciaa** [comment]
Me aswell i dont see any lag in movie. Just follow tree while watching character.

**Comment by Ancores** [comment]
Yeah, it's pretty much impossible to see it in the video, but it is there.
I've always had this problem with OTC and there's no lag at all using CipSofts Client.

**Comment by Ancores** [comment]
Made a new video, using an unmodified version of OTC on a server which has no lag at all with CipSoft's client.
https://www.youtube.com/watch?v=vdW5YPJj9aU

**Comment by Anastaciaa** [comment]
And now make move while you doing exactly same way using CipSoft client

**Comment by Ancores** [comment]
Using CipSoft client.
https://www.youtube.com/watch?v=f0nx4RkeY5c&feature=youtu.be

**Comment by Nu77** [comment]
He is saying which otclient sometimes is freezed when walking while cipsoft client not

**Comment by Anastaciaa** [comment]
In my opinion it looks like character legs moving faster in cipsoft client but the speed result is same as in otclient, even both movies time is similar that means you reached the destination at same time.

**Comment by Ancores** [comment]
Still the same problem.

**Comment by conde2** [comment]
try this:

    int footDelay = getStepDuration(true) / getAnimationPhases();

**Comment by gesior** [comment]
I get a lot of reports about lags with movement system from players (tibianus.org). This is serious problem of OTC. I think that developers should ignore everything else and focus on making movement system smooth, because client is unplayable on war/pvp servers.
I made antibot system that detects 100% bots, but players are angry, because client lags :(

---
Report about lag between steps with autowalk is a bit stupid, because SERVER calculate and execute steps of autowalk, but I must say that there is some problem with moving with autowalk - character sometimes teleport, espacially when character want to move diagonal.

**Comment by iryont** [comment]
If you want to receive help you need to give something from yourself. Make some pull requests, improve our code in any way, and we will see what we can do for you to help you achieve certain things in the public repository.

As you can probably notice in the repository pretty much every initial idea with some basic code as a proof of concept became a base for others to finish the work you have started. A recent example would be my idea regarding multi-line selection which was greatly improved by @edubart himself and finished by me later on (well, it still needs some fixes regarding highlighted words). This is pretty much how our work looks like, you give an idea with a proof of concept and if you can't finish it then most likely someone else will help you out.

**Comment by gesior** [comment]
Problem is that I got no idea what is wrong. I added ~50 'prints' in OTC LUA, ~20 in OTC C++ and ~50 in forgottenserver to view all packets, but I got no idea about animations and bugs with movement are not easy to reproduce - they are random, I ran same way 10 times with dragon behind and lagged only one time.

I write things that I know how to create, like PNG map generator:
https://github.com/gesior/otclient
but I got no idea about tibia animations and movement system :(

**Comment by diath** [comment]
You could always place a bounty on the issue if it's so important for you and you want someone to get interested in fixing this.

**Comment by iryont** [comment]
To be honest I have no idea what kind of problem you are having with OTClient. Can you record a video to show us the exact issue you are talking about? What do you mean by "animations and bugs with movement" and "they are random", @gesior.

**Comment by Zbizu** [comment]
I can confirm these lags. Going to large dragon lair filled with lava causes client lags.
cip clients uses like 35000 k of memory in task manager, otclient around 256000 k

I think it's amount of data processed
- for example damage animation (animatedText above creature when it's hit) is low fps on cip client, in otclient it's smooth
- render distance is probably too far (applies to multiple floors also)

**Comment by zeeb92** [comment]
"_If you want to receive help you need to give something from yourself. Make some pull requests, improve our code in any way, and we will see what we can do for you to help you achieve certain things in the public repository._" - **Iryont**

What does this even mean? He finds a bug and reports it so you guys who made the client can fix it and improve your work.

What should he give? He's clearly given enough; a bug report with videos.

Don't close this issue since it is still a problem in 2020.

**Comment by iryont** [comment]
This repository is no longer in active development stage therefore you are free to make your own changes and make a pull request if you feel your work is worth it.

Looking forward to pull requests from the community. I will gladly overview them myself.
