### ISSUE TITLE
Idle Animations

### ISSUE THREAD

**Issue by totolol123** [edubart/otclient#649]
With TFS 1.1 update we need idle group for OTClient, creature movements is very weird for now

**Comment by esfomeado** [comment]
:+1:

**Comment by ronpetit** [comment]
That's right, look how the idle animation looks in the lastest TFS

![error](https://cloud.githubusercontent.com/assets/5855265/8400894/fa4b2fc8-1def-11e5-8337-12094f5256a8.jpg)

**Comment by ronpetit** [comment]
@edubart this problem have 2 months for now, is too complex?, this really quit the beautifull view of the client, hate to know almost nothing about C++ :(

**Comment by iryont** [comment]
No, it isn't complex, but none of us play newest Tibia and we do not really have time for that right now.

Anyway, pull requests are welcome regarding this issue.

**Comment by LuigiLazzari** [comment]
Any update on this?

**Comment by iryont** [comment]
No, but pull requests are welcome though.

**Comment by Mignari** [comment]
I disagree about the complexity. It's a simple dat change, but hard to implement. I choose to remove the 'frame group' from the dat instead of implement in the OTC.

**Comment by daniofordon** [comment]
hello and how someone was able to fix it? I urgently need this fix: / how someone will have a solution for priv please GG: 25479648 Email : daniofordon@gmail.com

**Comment by Zbizu** [comment]
duplicate with #642 

animationPhase in Creature::internalDrawOutfit (src/client/creature.cpp) is either read incorrectly or new outfits idle frame is different than 0

**Comment by Marahin** [comment]
Just as previous speakers mentioned, I'd love to see (at least) a workaround for this. Having broken idle animations is terrible. 
At least point us in the right direction where should we seek for the solution, or how shall we look for it. 

It's a year now since it appeared. I know that it's open source and (possibly) not really profit-making project, but hell, it's awesome - if you don't have spare time, point community in a way that would maybe work things out. :)
