### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by crackcomm** [edubart/otclient#655]
The official client makes no problems even in Virtual Box but using OTClient Im getting freezes, usually when something happens on the screen (animations etc.), sometimes Im just getting logged out. I think my GPU should be enough for this.
It's possible to play sometimes so Im not sure what could be source of the problem.
I tried to compile client with LuaJIT - no changes.

ATI Radeon HD 4350 512 MB DDR2
Intel(R) Core(TM) i7 CPU         930  @ 2.80GHz
12 GB RAM

**Comment by HeavenIsLost** [comment]
This behavior the same with opengl and directx9(angle layer)?

**Comment by crackcomm** [comment]
I was not aware I can use DirectX on linux. I will try that asap.

**Comment by TheAifam5** [comment]
DirectX on Linux .. hahahha XD

**Comment by crackcomm** [comment]
@HeavenIsLost meant https://code.google.com/p/angleproject/ I think...

**Comment by crackcomm** [comment]
I Installed Windows and now Im getting this http://i.imgur.com/GIVssuF.png no driver detected...
I have a driver wtf is happening here?

**Comment by gesior** [comment]
I got many reports from playes with weak PCs that they got problems with moving on Tibianus.org. I will try to find reason on weekend.
For me it's hard to reproduce, because with 1 core (4.0GHz) and graphic card disabled (render all on CPU?) I still got 90+ fps.

**Comment by iryont** [comment]
Are you guys sure this is fps related issue? Perhaps it would be worth to test the client on some low end computer and see what is the bottleneck for you (either GPU or the CPU).

**Comment by LordHepipud** [comment]
I did made some reserach on that some time ago as some of my Players complained about that as well. It Looks like the Problem occures with OpenGL on older ATI Cards for example. Intel HD chipsets seem to have a Problem there sometimes as well.

For ATI Cards it didn't matter if it was a high end or low end Card. High-End NVidia Cards are working fine, but lower Cards are having a Problem as well - like the G210. The fps are very low, causing the game to be a Little laggy. Tested that with the mentioned G210 for example and the Client lagged. With the GT 980 Ti Phoenix for example everything is perfectly smooth.

~~~~Lord Hepipud~~~~

**Comment by gesior** [comment]
Are you sure that it's not HDD related?

This weekend I will try to check how often OTC reads files from disc when game is online [I got SSD in all PCs/laptops, so I can't see any lag, but on my PC in work I got network disc and it sometimes freez]. 

I will also try to delete all light effects from OTC and check change in FPS.

I will post results of my tests in this thread.

**Comment by LordHepipud** [comment]
I'm using a SSD myself and receiving this Problem while using a low Level graphic Card. So in my oppinion it's entirely graphic related.

~~~~Lord Hepipud~~~~

**Comment by diath** [comment]
There little to no disk I/O going on during playing so it's definitely not an issue. Quick perf run shows that the client spends most of the time in the MapView::draw function (which is not a surprise). Perhaps the rendering process could be optimized (somehow).

**Comment by gesior** [comment]
On my laptop turning off light effects gives 20-70% more FPS (60% on PoI).
Biggest problem is loading of new textures when you see them first time. I will try to make it preload all textures at start.

**Comment by iryont** [comment]
The spr file once loaded is cached within RAM. Textures should be loaded from RAM to VRAM pretty past.

Lighting is an issues because the blending operation is simply expensive and not an easy one if many lights are visible. Lighting system is never a trivial task in graphical applications if we are talking about performance.

**Comment by gesior** [comment]
One of milestones for OTC should be custom lighting system without so advanced effects.

but I think that most important is movement system. Current version is laggy. On high-end machines (1000 euro) it's not a big problem, but most of players got slow PCs or even.. laptops.

**Comment by iryont** [comment]
Actually light mapping is the simplest lighting you can create except for some build in lighting in OpenGL or DirectX. It's not advanced at all, but it is good in terms of final product which is similar to per pixel lighting. However, light mapping requires color blending which is unfortunately not a cheap operation if too many light sources are visible on the screen.

You can always optimize it a bit by rendering only certain amount of lights. If you have 20 lights on the map and most of them are not visible due to being overlapped by others (assuming replace composition mode) then there is no need to draw them.

**Comment by gesior** [comment]
Are lights rendered with each frame? I think that most of light effects are static like fire fields, lanterns etc., maybe there is a way to pre-render them once (all items lights) and then blend it with gamescreen every frame until light of some item change/player move.

**Comment by iryont** [comment]
Indeed they are rendered each frame. That's not a bad idea either, you can save a lot of computing power by only re-drawing buffer once any light changes (position, size, color, and so on). You are lucky, because the light buffer is following creature position just like frame buffer of the game-view meaning that you won't have to draw lights all the time during your movements (just once each step).

**Comment by Anastaciaa** [comment]
This can be walking function written wrong way. It depends from ping and for example when you decrease the FPS to 10, you can see that every step getting freeze while this behaviour not happen in normal cipsoft client.

**Comment by totolol123** [comment]
I noticed some freezes when you walk around any place, surely is something related to the walking side
