### ISSUE TITLE
forgottenserver and otclient boost version problem (codeblocks)

### ISSUE THREAD

**Issue by gesior** [edubart/otclient#670]
If someone install 'forgottenserver' libraries for Visual Studio (step 2: https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows#2-install-the-required-software ), it will block possibility to compile OTClient in CodeBlocks.

Old .cbp files will work fine, but if you try to install OTClient source to new dir and run 'cmake-gui.exe', it will detect Boost 1.57 (forgottenserver boost) and set it's directory as 'Boost_DIR' (in place of OTclient boost 1.55).

Then OTclient compilation will break at linking, because of some missing functions in boost.

I described how to fix it in 'edit 2' in post: https://otland.net/threads/compiling-otclients-latest-source-with-microsoft-visual-studio-2013.204849/page-7#post-2258352

**I UNDERSTAND that it's not OTclient bug, but I think that there should be some notice in Windows Compiling (Wiki) about it, as many people that use OTClient want also compile 'TFS 1.0+'**

**Comment by iryont** [comment]
Why would the linking break? Are you trying to feed the CMake with 1.55 boost libraries and 1.57 headers?

Just for the record - CMake is capable of reading boost version from version.hpp file available within headers of the boost libraries. However, on Windows you do not usually name boost libraries properly - instead of e.g. libboost_system-mt-1_55.a you have libboost_system-mt.dll.a and the CMake is now unable to determine the true version of the library itself, thus it will try to link with it even if libraries are not compatible with headers.

**Comment by gesior** [comment]
Linking break, because some functions are deprecated in 1.57 and it cannot find some functions required by OTClient.
Anyway, after 2 days of errors [I also could not compile without 'debug', without 'static lib' and my client worked ONLY on my pc!].
I did install Win7 on VMWare Player and keep there clean windows with CodeBlocks only for OTClient compilation.

**Comment by TheSumm** [comment]
Just define the boost directory manually, I don't know what your setup is but in QtCreator I would just add:
-DBOOST_DIR="C:/path/"
