### ISSUE TITLE
Version 11 or later support

### ISSUE THREAD

**Issue by LucasCPrazeres** [edubart/otclient#864]
Is it possible to upgrade to the current version using the same .dat and .spr method of this topic?

Http://www.tibiaking.com/forum/forums/topic/71565-tools-ot-1140-updated-itemeditor-remeres-objectbuild/

This includes support for store, prey, imbuement and inspect

**Comment by Tekadon58** [comment]
up

**Comment by djblah** [comment]
otclient graphic sprite slow 10.98
some way to solve that

**Comment by Felipe1993** [comment]
bump im looking for tibia 11 support too

**Comment by djblah** [comment]
someone who can compile me otclient
if(version >= 1050) {
enableFeature(Otc::GameEnhancedAnimations);
}

change


if(version <= 1050) {
enableFeature(Otc::GameEnhancedAnimations);
}

**Comment by avelino** [comment]
Does **otclient** intend to support Tibia 11 protocol?

**Comment by Tekadon58** [comment]
Looks like the otclient does not want to go anywhere kkkkkk. It seems he died :( There is no gamestore.

**Comment by andersonfaaria** [comment]
you guys gotta grow up and stop thinking the owner of everything will have to update it just for you. The project is HERE, NOW. Contribute or shut up.

If you want it to support tibia 11, read the source files and check how they made for other versions to log in, if you think the project is dead it's because there are way too many petty people out there who feed from this repository without ever paying it back with the answers they find by themselves.

This community is so trashy that I've even used it to prove an argument about open source projects being used in the big tech companies.

Most of the servers out there who use otclient already solved all the issues it has, still, this repository is each day with less and less people retributting.

This will only be dead if someone fucking delete the whole repository and all the forks.

**Comment by Izzaki** [comment]
> someone who can compile me otclient
> if(version >= 1050) {
> enableFeature(Otc::GameEnhancedAnimations);
> }
> 
> change
> 
> if(version <= 1050) {
> enableFeature(Otc::GameEnhancedAnimations);
> }

Thank you so much:)
it really seems to work:) 
I do prefer use in protocollogin.lua :
g_game.disableFeature(GameEnhancedAnimations);
