### ISSUE TITLE
Sell All bugs

### ISSUE THREAD

**Issue by andersonfaaria** [edubart/otclient#891]
There's three issues related to Sell All.

1. Sell all doesn't work if you have more than 100 items (for stackable)
2. The function that returns your items (onPlayerGoods) is unable to count more than 255 items (for stackable). If you have 500 vials for instance, it will always show only 255. I've searching very deep into source and notice that it only has 8 bits for counting the quantity but even increasing this number it didn't worked.
3. The function you use on module npctrade.lua for sellall is getting wrong information.
```
function sellAll()
  for itemid,item in pairs(playerItems) do
    local item = Item.create(itemid)
    local amount = getSellQuantity(item)
    if amount > 0 then
      g_game.sellItem(item, amount, ignoreEquipped:isChecked())
    end
  end
end
```
It returns not only sellable items but also the buyable ones. If you have an item that is buyable in your inventory but not sellable and you click sell all it will try to sell the item that is not sellable returning an error in source. 

### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Environment
Latest release, 10.76 server.

**Comment by Codex-NG17** [comment]
That is because an `unsigned byte` only has a range value of 0 to 255. An unsigned byte can not hold a value of less than 0 or greater than 255.

Where as a `signed byte` can not hold a value less than -128 or greater than 127, because its range value is -128 to 127.

Knowing the datatypes in essential if you want to mess around with the sources, essentially after reading the 1st 5 chapters of any programming book on C++ the code you are looking at will make a lot more sense.

https://msdn.microsoft.com/en-us/library/s3f49ktz.aspx

**Comment by andersonfaaria** [comment]
even increasing to 32bit the value stays the same, that's not the problem. The function is wrongly made.
The 8bit is considered for max stackable for one item only, it means you can't have a stack of runes greater than 255 in one slot (same for tfs), but the function that gets the quantity should sum each quantity of each slot, which it isn't currently doing.

**Comment by andersonfaaria** [comment]
after digging a little up, the 1 topic is not a problem with OTC, instead it's related to npc lib of tfs that doesn't understand higher than 100 stackable values. Instead of trying to remove a higher amount than 100, it should check whether the quantity is higher than 100 and make a loop and counting the sold quantities.

So, we are still with 2 and 3, any thoughts anyone?
The 2 is bounded to this function, the error is here somewhere 

```
void ProtocolGame::parsePlayerGoods(const InputMessagePtr& msg)
{
    std::vector<std::tuple<ItemPtr, int>> goods;

    int money;
    if(g_game.getClientVersion() >= 973)
        money = msg->getU64();
    else
        money = msg->getU32();

    int size = msg->getU8();
    for(int i = 0; i < size; i++) {
        int itemId = msg->getU16();
        int amount;

        if(g_game.getFeature(Otc::GameDoubleShopSellAmount))
            amount = msg->getU16();
        else
            amount = msg->getU8();

        goods.push_back(std::make_tuple(Item::create(itemId), amount));
    }

    g_game.processPlayerGoods(money, goods);
}
```

at first I thought about enabling this feature:
```
 if(g_game.getFeature(Otc::GameDoubleShopSellAmount))
            amount = msg->getU16();
        else
            amount = msg->getU8();

```

but it didn't worked out :/

For the third one, I've made a workaround in Lua, but we should use a better approach of getting goods from a player instead of using every item considered in both buy and sell list of a npc.

**Comment by diath** [comment]
2. isn't really a bug or limitation of the client, as @Codex-NG17 said, the protocol simply uses an 8-bit number for the amount which limits the amount to 255 items. As you noticed there's a feature flag to make it a 16-bit integer however the server will not know that you'd actually like to use a 16-bit integer for it so you you would have to edit it on the server side as well and this is not an issue with OTClient:

https://github.com/otland/forgottenserver/blob/master/src/protocolgame.cpp#L1573

**Comment by andersonfaaria** [comment]
@diath I'm a little newbie to c++ so I couldn't fully understand the code but I think that it sends 8-bit for quantity because you can have a single stack of more than 255 items, but if you are iterating for all the items the player have should you have more stacks of the same item in the map? I mean, imagine I have 3 stacks of 100 runes. Should my vector be 100, 100, 100 instead of just 255? 

If the problem is in TFS, shouldn't we blocked in OTC a limit for 100 items of the same type for the sell all (if the player wants to sell more he just have to click again on the button). I tried to do that changing the modules but the way the function of ignoreChecked was made make things a little difficult when you have some of the items in the arrow slot. You may have 500 UH's but 100 in the arrow alot, it will return 0 in the sell all quantity if you limit stuff. It's really annoying

**Comment by diath** [comment]
The stacks are summed up on the server side, so if you have 3 stacks of 100 runes, it will hold the number 300 for the count of the runes (it essentially maps the ID to the count rather than sending individual stacks) which is then hard-capped at 255 (the maximum an unsigned 8-bit number can hold).
Likewise when the server receives the sale packet, it can read only a maximum of 255 items (https://github.com/otland/forgottenserver/blob/master/src/protocolgame.cpp#L931) and while the limit of 100 is artificial in OTClient you still won't be able to sell quantities larger than 255 at a time. Even if you made it count the stacks properly, you would still have to loop through the amount and keep subtracting 255 and sending the remainder, essentially sending multiple packets until you're done. This can be done but I don't believe it's an issue with OTC per se, sounds more like some personal feature that you'd like to have in which case I don't think it warrants an issue. However the ignoreEquipped flag not working as intended sounds like an actual issue that should be addressed.

**Comment by andersonfaaria** [comment]
I believe it is an issue since the Sell all button doesn't work as intended. If it's the case, we should make it work for the client side and then create a PR on tfs too. 
It's just changing from 8 bit to 16 bit?

By the way, I've managed to sell in chunks only editing in the client side
```
-- Modified on 17/10 by Anderson
-- Edit: it was trying to sell wrong items
-- Edit2: now it iterates to sell items with more than 100 in count

function sellAll()
  for itemid, item in pairs(playerItems) do
	local data = getTradeItemData(itemid, SELL)
    if data then
		local item = Item.create(itemid)
		local amount = getSellQuantity(item)
		if amount > 0 then
			if amount > 100 then
				repeat
					g_game.sellItem(item, 100, ignoreEquipped:isChecked())
					amount = amount - 100
				until amount <= 100
				g_game.sellItem(item, amount, ignoreEquipped:isChecked())
			else
				g_game.sellItem(item, amount, ignoreEquipped:isChecked())
			end
		end
    end
  end
end
```
I've also fixed the issue where it was trying to sell buyable (but not sellable) items to npcs when pressing sell all, but it looks very bad because this functions weren't supposed to work like this. But this way it will appear. 
'You sold 100x mana potion to npc'
'You sold 100x mana potion to npc'
'You sold 55x mana potion to npc'
which is very annoying and bad to see. So sooner or later I'll have to edit the lib to accept more than a 100 in one single sell and then changing both source and client to get the right amount of the item instead of just 8 bit :/

I'm not sure if I'm making myself clear but you are free to ask if you didn't understand anything, sometimes I'm too anxious to answer and don't explain things very well.

I'll try to do that and will update this discussion with my progress, it would be nice if you could assist me at least in this beginning because I don't really now where is each thing on the sources and it take my too much time to understand how things were designed. For the next PR's and issues I intend to walk on my own.

**Comment by diath** [comment]
>I believe it is an issue since the Sell all button doesn't work as intended. If it's the case, we should make it work for the client side and then create a PR on tfs too.

You're right, it slipped my mind that the sell all feature is an actual client feature.


> It's just changing from 8 bit to 16 bit?

If you want to be able to sell more than 255 at a time then yes you would have to change the data type and adjust the NPC system accordingly, however it will only work with your version of the server and client.


>By the way, I've managed to sell in chunks only editing in the client side

That's pretty much what I was talking about, and since you're right that it's an issue with the client you should submit a Pull Request with the change.


>[...] But this way it will appear.

Unfortunately this is how it will look like if you make the feature generic and not tailored for a custom server.

**Comment by andersonfaaria** [comment]
I really intended to create a PR also for tfs, this way both otc and server will be in unison.
But first, I have to make all the changes xD. 

Thanks for the explanation, sometimes I feel a little bit lost when trying to work on tfs and otc environments but having someone to talk is really helpful.

**Comment by andersonfaaria** [comment]
@diath I'm having some trouble with the server side editions, it seems that even changing both the functions parseSell and parseBuy it isn't working, perhaps something related to the the first link you sent:
https://github.com/otland/forgottenserver/blob/master/src/protocolgame.cpp#L1573

So far all I managed to do is make the sell option stop working :(

**Comment by diath** [comment]
I can't tell what's wrong without seeing the changes however you shouldn't be changing anything in the protocol because that would make it incompatible with Cip's client. You should just rework the NPC system so it accepts up to 255 items at a time (from 100) instead and make OTC loop through the items to sell them all by chunks (as discussed earlier).

**Comment by andersonfaaria** [comment]
Since otc came to replace cip's client I'm interested in a solution regardless of what I'll break in the vanilla one.
