### ISSUE TITLE
Problem!

### ISSUE THREAD

**Issue by KotZletY** [edubart/otclient#912]
I don't know if it's allowed here to post errors since this is a problem issue, if not allowed, i'm sorry.
At the time of compilation the following errors are pointed out, remembering that the last version with the last commits without any changes:

C:\Users\*****\Desktop\otclient-master\src\framework\stdext\time.cpp||In function 'void stdext::millisleep(std::size_t)':|
C:\Users\*****\Desktop\otclient-master\src\framework\stdext\time.cpp|46|error: 'std::this_thread' has not been declared|
C:\Users\*****\Desktop\otclient-master\src\framework\stdext\time.cpp||In function 'void stdext::microsleep(std::size_t)':|
C:\Users\*****\Desktop\otclient-master\src\framework\stdext\time.cpp|51|error: 'std::this_thread' has not been declared|
CMakeFiles\otclient.dir\build.make|241|recipe for target 'CMakeFiles/otclient.dir/src/framework/stdext/time.cpp.obj' failed|
CMakeFiles\Makefile2|66|recipe for target 'CMakeFiles/otclient.dir/all' failed|
CMakeFiles\Makefile2|78|recipe for target 'CMakeFiles/otclient.dir/rule' failed|
C:\Users\*****\Desktop\build\Makefile|163|recipe for target 'otclient' failed|

Details about the above error:
https://hastebin.com/xuqekoruxe.tex

**Comment by diath** [comment]
https://github.com/meganz/mingw-std-threads

**Comment by diath** [comment]
I figured I'd elaborate on this since I just dropped the link without mentioning anything. Basically what happens is that MinGW on Windows doesn't fully implement the standard threading library so there are three options:
* Compile using Visual Studio rather than MinGW
* Force otclient to use Boost.Thread instead of the standard threading library by commenting out the preprocessor check in framework/stdext/thread.h
* Drop the files from the repo I linked above into the project and include it in the thread.h file

**Comment by edubart** [comment]
You could use mingw-w64, it does support, mingw32 doesn't.
mingw-w64 compiles to 32 or 64 bits archicheture
mingw32 only to i686

**Comment by diath** [comment]
I just tested mingw-w64 and it seems that you're right but only if the POSIX threading model is chosen during the installation, the Win32 one will not work. Posting it here just in case anyone runs into the issue.

**Comment by conde2** [comment]
@diath @edubart

Is it possible to use the sames pre compiled libraries from mingw32 in the mingw-w64 ?

**Comment by manuloku** [comment]
Where can i take the x64 libs? it will be really helpful!
