### ISSUE TITLE
OTC w/ directX (error runtime library)

### ISSUE THREAD

**Issue by helliot1** [edubart/otclient#926]
Hello,

I've finally been able to compile OTC with code :: blocks, and now it's with Directx. But I have a problem, when I open the client got a error, and it don't open.

![error](https://user-images.githubusercontent.com/34548471/34002724-84ca730c-e0da-11e7-9855-9979ab25ac0e.png)

**(I'm using the OTC 0.6.6)**

I had many errors to compile from 'boostlibrary'. And I was able to resolve this errors, in the following way, I downloaded Boost-1.63 and compiled it with Gcc. I configured the variable for BOOST / BOOST_ROOT / BOOST_ROOT_OTCLIENT to redirect to the 'C: \ boost_1_63_0' directory and I had no error, just 'Warnings'. But when I get into the OTC, this error appears.

Note: I have not made any changes to the OTC. I just downloaded and compiled it with Code :: Blocks.

When I get this error, create a debug.txt file in otc folder and inside have:
`err: egl::Surface::initialize(109): Unable to set present parameters: 0x80004001`

**Comment by okk3** [comment]
I've updated the Wiki-Page that regards the compilation on Windows with DX9 Layer Support.

You can now download the SDK I uploaded to my github and follow the instructions, if you have any problem just contact me.

Kindest Regards,
Okke

**Comment by reyhammer** [comment]
@okk3, with a lot of effort I tried to compile with OpenGLES 2 the "DirectX" of OTClient.
However, using msvc2017 or msvc2015 I got in a lot of problems. On MSVC2017 I used msv140 [from 2015].

Using the library that should be compatible with x86 and x64 architecture, I was stuck in compiling process (undefined symbols [architecture glitches]), when using x86 version I was able to compile successfully, however the client does not open, and does not give any crash message. Using lib(SDK) I got the same problem, and lib with the x86 dlls the same problem, client does not open.

No crash reports.

I got this crash report when using different types of DLL.
[crashreport.log](https://github.com/edubart/otclient/files/2213908/crashreport.log)

![image](https://user-images.githubusercontent.com/11477038/43003009-426bbf5c-8c01-11e8-8ce3-4fd66254cca6.png)

![image](https://user-images.githubusercontent.com/11477038/43003013-46dc2c34-8c01-11e8-82c6-ab9f79ae1ce9.png)

![image](https://user-images.githubusercontent.com/11477038/43003036-5e3bbc32-8c01-11e8-91a8-55497768237d.png)

This is the way I included the files inside **C:\otclient-sdk-master**
[otclient-sdk-master.zip](https://github.com/edubart/otclient/files/2213918/otclient-sdk-master.zip)

**Comment by reyhammer** [comment]
I tried using only library name instead of path, in the first time I said it was impossible to find the library, so I added into  additional library directories, and it compiled just fine, however, same error to open the client.

Now I tried a different test, removed OPENGL_ES=2 from preprocessor defs, in order to compile standard version with those libraries linked. It does not open either, as well as does not generate any crash report.

![image](https://user-images.githubusercontent.com/11477038/43034982-468822d0-8cbd-11e8-8c94-a38b9d8fe123.png)

![image](https://user-images.githubusercontent.com/11477038/43034983-4ac5f2c8-8cbd-11e8-814f-f34f30235b77.png)

![image](https://user-images.githubusercontent.com/11477038/43034984-51b6df16-8cbd-11e8-89da-2ebe0a0e3574.png)
