### ISSUE TITLE
help bug jump walking on parcels or items with elevation 7.x 7.7 / 7.4

### ISSUE THREAD

**Issue by Felipe1993** [edubart/otclient#930]
Need help with this issue i thought it was fixed but the code doesn't works

this is the original code:

`    if(getClientVersion() <= 740) {
        const TilePtr& fromTile = g_map.getTile(m_localPlayer->getPosition());
        if (fromTile && toTile && (toTile->getElevation() - 1 > fromTile->getElevation()))
            return false;
    }`

i tested changing the 740 to 770 and to 772 but when i try to walk over two parcels or more the character try to walk over it, and it makes the beging of the character jump

example about how its works now:
https://media.giphy.com/media/3oEjHSeZ25mwItpxgk/giphy.gif

how it should works:
https://media.giphy.com/media/3oEjI3Rf2trrQN1ufu/giphy.gif

any idea?

**Comment by EgzoT** [comment]
> i tested changing the 740 to 770 and to 772 (...)

It's normal because `if(getClientVersion() <= 740)`

No all OTClient contributors play or played on protocol <= 740, so you may describe something in difference between <= 740 and > 740. It's may be very helpfull.

_You may paste imgs/gifs directly to github comment by dragging and dropping, so that will be simpler to you and us._

**Comment by Felipe1993** [comment]
something like
`if(getClientVersion() <= 740 > 770)` right?
thanks for your reply @EgzoT but what im saying is that the code doesn't works :c 
culd u help me a little bit more pls?

regards bro

**Comment by EgzoT** [comment]
This problem was fixed by @EvulMastah 
[Properly check tile elevation in older protocols (13789c5)](https://github.com/edubart/otclient/commit/13789c56128a694b3236717359cfb2cc04f627e0#diff-7f71a92de20504e8a5636b4317ea67b2)

But I don't know why this don't work at your OTClient.
You are sure than you compiled the last OTClient version?
Maybe give server name and I check it.

**Comment by Felipe1993** [comment]
I use otx 2 77.2

i checked and the changes doesn't works
could u help me? pls @EgzoT 
Regards
