### ISSUE TITLE
otclient Hotkey

### ISSUE THREAD

**Issue by CerberusBR** [edubart/otclient#952]
Otclient reconhecer mouse nas hotkeys , podendo add btão do mouse na hotkey do client

**Comment by EgzoT** [comment]
If you want get response to your issue, write it in english.

**Comment by Eternal-Scripts** [comment]
Translating: support for macro buttons of mouse like hotkeys.

**Comment by EgzoT** [comment]
Best way: Use application dedicated for your mouse and set key combination in this app, for example 'F1' keyboard button.

Why?
Because mouse with more than one key, may have own system for this or it set own actions for them. It's not easy to create method to interpetate all this signals from mouse for various different mouses.
This mouses must have own drivers, so they need special app for these additional keys, because these buttons is not authorized by standards, and devs don't know how to interpreted these signals.

For example some offices mouses have two additional buttons and it's binded with keyboard key 'PageUp' and 'PageDown', and not all have special drivers/app to bind something other to them.

Other situation is with Xbox joystick who have own standards in Windows (in android too) and other joysticks or special drivers/app (for example drivers with app for PS joystick) retain this standard, and it's have sense to support them.
