### ISSUE TITLE
Extended OP ClientSide

### ISSUE THREAD

**Issue by tuxico** [edubart/otclient#958]
ERROR: caught a lua call to a bot protected game function, the call was cancelled

> -- hooked events
> function onInventoryChange(player, slot, item, oldItem)
>   if slot > InventorySlotPurse then return end
> 
>   if slot == InventorySlotPurse then
>     if g_game.getFeature(GamePurseSlot) then
>       purseButton:setEnabled(item and true or false)
>     end
>     return
>   end
> 
>   local protocolGame = g_game.getProtocolGame() 
>   local itemWidget = inventoryPanel:getChildById('slot' .. slot)
>   if item then
>     if protocolGame then
>     local itemID = item:getId()
>     protocolGame:sendExtendedOpcode(1, itemID)
>     end
>     itemWidget:setStyle('InventoryItem')
>     itemWidget:setItem(item)
> 
>    --itemWidget:setTooltip('Item Name: ' .. item:getName() .. '\n' .. 'Server-ID:' .. item:getServerId() .. '\n' .. 'Client-ID: ' .. item:getId())
>   else
>     itemWidget:setStyle(InventorySlotStyles[slot])
>     itemWidget:setItem(nil)
>   end
> end

Bot Protection Turn Off
Recompiled 300x.

**Comment by TheSumm** [comment]
You did not really solve it, since the bot protection was working as intended. Whenever you send an action ( `sendExtendedOpcode` in this case ) without it being triggered by user input, the bot protection avoids that.

If you want to keep this module, you are right to disable the bot protection. However, you might want to reconsider whether you are taking the right approach here. From what I can see, you are sending an itemid to the server whenever the inventory changes. You do not have to do that since the server already knows that the inventory changed. After all the server is the one who told the client about this change.

**Comment by tuxico** [comment]
How can keep this without disable bot protection??
