### ISSUE TITLE
Something wrong in getStepDuration?

### ISSUE THREAD

**Issue by Acedayz** [edubart/otclient#976]
I've been trying to solve the movement issue that many people are having (lag between every step) and came across this line in getStepDuration():
```
if(g_game.getClientVersion() >= 900)
        interval = (interval / g_game.getServerBeat()) * g_game.getServerBeat();
```

Am I missing something or does that code not do anything at all?
It seems like it just sets interval to the value it already is

**Comment by Anastaciaa** [comment]
This code doesnt do anything at all. If you want to solve this problem you must add next step schedule before finishing previous step. Same like in normal tibia client.

**Comment by diath** [comment]
This code simply rounds the interval to a multiple of the server beat to keep it synchronized. The reason why it works is that it's an integer division, and integer division in C++ won't produce a float but instead will round towards nearest zero (for example (732 / 50) * 50 = 700). This is slightly wrong though because, in comparision, the flash client rounds the division up so the actual code should be:
```c++
interval = std::ceil(interval / (g_game.getServerBeat() * 1.f)) * 50;```

**Comment by TheSumm** [comment]
@Anastaciaa That's incorrect.

Both interval and server_beat are `int`s. As a consequence this line sets `ìnterval` to the maximum multiple of `getServerBeat` that is lower than interval.
