### ISSUE TITLE
Compilling Error

### ISSUE THREAD

**Issue by SuggestName** [edubart/otclient#982]
I followed the whole compilation tutorial by VCPKG, but still I still have this error when trying to compile otclient

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'libboost_thread-vc141-mt-x64-1_66.lib'	otclient	C:\Users\-\otclient\vc14\LINK	1	

I compile TFS with VCPKG without problem nor one ...

**Comment by VagnerDomingues** [comment]
just a reminder, english people don't use nor one to enfatize, just we brasilian folks do that in our own language. what they do is "without a problem" using the a you can achieve the same effect..

now please tell me how could you compile it? i'm trying to use vcpkg but the links are all messed up, then i tried to inject manually the paths to the libs, everything is looking messy i could only achieve compilation with olders commitments like commit: a6c7269 as release 32bit and inserting glew32.dll, zlib.dll (x32 too) and openAl.dll all manually because they were not compiling but at least the build was finishing... any maintainers to help us out?

**Comment by okk3** [comment]
If you check older versions of the Compiling on Windows page you'll see one commited by me, just follow that and you'll be good, I even added DX9 support and you can compile all that using MSVC15.

Best Wishes,
Okke
