### ISSUE TITLE
Extra Panel

### ISSUE THREAD

**Issue by EmersonHenriique** [edubart/otclient#991]
Hello have code from extra panel?
https://i.imgur.com/PCWOjw9.png
https://otland.net/threads/solved-second-right-panel.252286/

**Comment by EgzoT** [comment]
It's easy, I may add this but... I have now open pull request in gameinterface.lua module.
#974
And its will create conflict.

Look at gameLeftPanel in gameinterface.lua to show how to build another gamePanels.

**Comment by EmersonHenriique** [comment]
Could you help me with this extra panel code on the right side?

**Comment by Felipe1993** [comment]
i want it too

**Comment by Felipe21** [comment]
need this too please someone implement it pls

**Comment by Felipe21** [comment]
> It's easy, I may add this but... I have now open pull request in gameinterface.lua module.
> #974
> And its will create conflict.
> 
> Look at gameLeftPanel in gameinterface.lua to show how to build another gamePanels.

can you give me the code to get extra right pannel, please?
@EgzoT

**Comment by okk3** [comment]
@Felipe21 Why dont you look at gameLeftPanel in gameinterface.lua in order to create a new panel? Nothing's really preventing you from doing it.

I'll help out if I see you're at least trying, people usually do not work for free. Helping you with your problems in particular will not contribute with anything to the project in any matter.

Best Wishes,
Okke

**Comment by Felipe21** [comment]
@okk3 
hey i added the code
in here:
Client_options 
Game_interface 

i copied the code from a client that already had the extraright pannel to my files
but went to open otclient exe a window pop up with the msg that game interface folder cant load

king regards

**Comment by okk3** [comment]
Hello @Felipe1993 ,

could you supply me with the stack traceback? :)

Best Wishes,
Okke

**Comment by EmersonHenriique** [comment]
@Felipe21 
code very confusing and could not activate

**Comment by Felipe21** [comment]
@EmersonHenriique indeed its not working
@okk3 bump ! help me pls

**Comment by Felipe21** [comment]
bump

**Comment by okk3** [comment]
Holy Balls, are you guys still stuck on this? I asked for the errors 11 days ago yet no one could actually provide anything, are you guys even developers?

Since we do not have crystal balls we need to know what the problem isn't liking on the code, please send what the console says and not what you think it is.

Much appreciated,
Okke

**Comment by Felipe21** [comment]
ERROR: Unable to load module 'game_interface': LUA ERROR:
/game_interface/gameinterface.lua:66: attempt to index global 'showTopMenuButton' (a nil value)
stack traceback:
	[C]: in function '__newindex'
	/game_interface/gameinterface.lua:66: in function 'init'
	/game_interface/interface.otmod:34:[@onLoad]:1: in main chunk
	[C]: in function 'ensureModuleLoaded'
	/init.lua:46: in main chunk
FATAL ERROR: Unable to load 'game_interface' module
